# spring.profiles → spring.config.activate.on-profile
# sample line change
# sample line change2bc
spring:
  profiles: dev
server:
  port: 8000
---
spring:
  profiles: test
server:
  port: 9000
# spring:   THE BELOW DOES NOT WORK!
#   config:
#     activate:
#       on-profile: dev
# server:
#   port: 8000
# ---
# spring:
#   config:
#     activate:
#       on-profile: test
# server:
#   port: 9000